import { mysqlTable, varchar, serial, text, timestamp, int } from 'drizzle-orm/mysql-core';

export const customers = mysqlTable('customers', {
  id: serial('id').primaryKey(),
  name: varchar('name', { length: 255 }).notNull(),
  contactName: varchar('contact_name', { length: 255 }),
  phone: varchar('phone', { length: 50 }),
  email: varchar('email', { length: 255 }),
  region: varchar('region', { length: 100 }),
  implementationType: varchar('implementation_type', { length: 100 }),
  vehicleCount: int('vehicle_count').default(0),
  createdBy: varchar('created_by', { length: 150 }).default('guest'),
});

export const serviceRequests = mysqlTable('service_requests', {
  id: serial('id').primaryKey(),
  createdAt: varchar('created_at', { length: 100 }),
  source: varchar('source', { length: 100 }),
  region: varchar('region', { length: 100 }),
  status: varchar('status', { length: 50 }).default('New Lead'),
  implementationType: varchar('implementation_type', { length: 100 }),
  customerName: text('customer_name'),
  contactName: varchar('contact_name', { length: 255 }),
  phone: varchar('phone', { length: 50 }),
  email: varchar('email', { length: 255 }),
  address: text('address'),
  mapLink: text('map_link'),
  coordinates: varchar('coordinates', { length: 100 }),
  
  newQty: int('new_qty').default(0),
  migrateQty: int('migrate_qty').default(0),
  tradingQty: int('trading_qty').default(0),
  serviceQty: int('service_qty').default(0),
  otherQty: int('other_qty').default(0),
  accessories: text('accessories'),
  
  requestedPerson: varchar('requested_person', { length: 100 }),
  salesPerson: varchar('sales_person', { length: 100 }),
  salesType: varchar('sales_type', { length: 100 }),
  
  projectValue: varchar('project_value', { length: 100 }),
  priceDetails: text('price_details'),
  comment: text('comment'),
  
  issueDescription: text('issue_description'),
  location: varchar('location', { length: 100 }),
  paymentStatus: varchar('payment_status', { length: 50 }),
  amount: varchar('amount', { length: 50 }),
  vehicleDetails: text('vehicle_details'),
  notes: text('notes'),
  jobStatus: varchar('job_status', { length: 50 }).default('Pending'),
  createdBy: varchar('created_by', { length: 150 }).default('guest'),
});

export const messages = mysqlTable('messages', {
  id: serial('id').primaryKey(),
  role: varchar('role', { length: 20 }).notNull(), // 'user' or 'assistant'
  content: text('content').notNull(),
  timestamp: timestamp('timestamp').defaultNow(),
  username: varchar('username', { length: 255 }),
});

export const salesplusEntries = mysqlTable('salesplus_entries', {
  id: serial('id').primaryKey(),
  synohubRequestId: int('synohub_request_id'),
  salesPlusId: int('sales_plus_id').default(0),
  salesPlusDate: varchar('sales_plus_date', { length: 20 }),
  salesPlusSource: varchar('sales_plus_source', { length: 100 }),
  salesPlusRegion: varchar('sales_plus_region', { length: 100 }),
  salesPlusStatus: varchar('sales_plus_status', { length: 50 }),
  salesPlusImplementationType: varchar('sales_plus_implementation_type', { length: 100 }),
  locatorPlan: varchar('locator_plan', { length: 100 }),
  salesPlusPrice: varchar('sales_plus_price', { length: 100 }),
  salesPlusProjectValue: varchar('sales_plus_project_value', { length: 100 }),
  salesPlusCompanyName: text('sales_plus_company_name'),
  salesPlusCustomerName: varchar('sales_plus_customer_name', { length: 255 }),
  salesPlusPhone: varchar('sales_plus_phone', { length: 50 }),
  salesPlusEmail: varchar('sales_plus_email', { length: 255 }),
  salesPlusDesignation: varchar('sales_plus_designation', { length: 255 }),
  salesPlusAddress: text('sales_plus_address'),
  salesPlusAddressMap: text('sales_plus_address_map'),
  salesPlusAddressCoordinates: varchar('sales_plus_address_coordinates', { length: 100 }),
  salesPlusPerson: varchar('sales_plus_person', { length: 50 }),
  salesPlusType: varchar('sales_plus_type', { length: 100 }),
  salesPlusQuantityNew: int('sales_plus_quantity_new').default(0),
  salesPlusQuantityMigrate: int('sales_plus_quantity_migrate').default(0),
  salesPlusQuantityTrading: int('sales_plus_quantity_trading').default(0),
  salesPlusQuantityService: int('sales_plus_quantity_service').default(0),
  salesPlusQuantityOthers: int('sales_plus_quantity_others').default(0),
  salesPlusSupplier: varchar('sales_plus_supplier', { length: 255 }),
  salesPlusAccessories: text('sales_plus_accessories'),
  salesPlusComment: text('sales_plus_comment'),
  salesPlusRequestedBy: varchar('sales_plus_requested_by', { length: 50 }),
  scheduleNote: text('schedule_note'),
  schedulePhone: varchar('schedule_phone', { length: 50 }),
  priority: varchar('priority', { length: 50 }),
  clientName: text('clientName'),
  itcUsername: varchar('itcUsername', { length: 255 }),
  itcPassword: varchar('itcPassword', { length: 255 }),
  projectImplementationType: varchar('projectImplementationType', { length: 100 }),
  leadType: varchar('leadType', { length: 100 }),
  tradeNumber: varchar('tradeNumber', { length: 100 }),
  notes: text('notes'),
  createNewNob: int('create_new_nob').default(0),
  existingCustomer: int('existing_customer').default(0),
  customerId: int('customer_id').default(0),
  additionalContactDetails: text('additional_contact_details'),
  synohubRequestedPerson: varchar('synohub_requested_person', { length: 100 }),
  createdAt: timestamp('created_at').defaultNow(),
});
